<?php

namespace App\Component\Packages\Example\Greeting;

use App\Component\Routing\Controllers\BaseController as Controllers;

/**
 * 
 * Author : harrieanto31@yahoo.com | Web:https://youreinspire.com
 * -----------------------------------------------------------------
 * Created : 30/Oct/2017
 * As Repsoitoriey Framework Components
 * This class generated by system
 * Feel free to tinker this method class conformist your need
 * -----------------------------------------------------------------
 * Github  :   https://github.com/harrie-xo
 * E-mail  :   harrie@youreinspire.com | harrieanto31@yahoo.com
 * 
 */

class GreetingController extends Controller
{
	public function index()
	{
		echo "This is greeting page";
	}
}